name: Acheron Blade
automation:
  - type: variable
    name: used
    value: "0"
  - type: condition
    condition: choice == "dark"
    onTrue:
      - type: counter
        counter: "Acheron Blade: Dark Blessing"
        amount: "1"
        errorBehaviour: raise
      - type: target
        target: self
        effects:
          - type: temphp
            amount: 1d4+4
      - type: variable
        name: used
        value: "1"
    onFalse: []
    errorBehaviour: neither
  - type: condition
    condition: choice == "disheartening"
    onTrue:
      - type: counter
        counter: "Acheron Blade: Disheartening Strike"
        amount: "1"
        errorBehaviour: raise
      - type: target
        target: all
        effects:
          - type: ieffect2
            name: Disheartened
            effects:
              save_dis:
                - all
            tick_on_caster: true
            end: true
            duration: "2"
            desc: The target has disadvantage on the next saving throw it makes before the
              end of your next turn. The creature ignores this effect if it’s
              immune to the frightened condition
            buttons:
              - label: Remove Effect
                automation:
                  - type: remove_ieffect
                verb: had disadvantage on a saving throw.
                style: "1"
      - type: variable
        name: used
        value: "1"
    onFalse: []
  - type: condition
    condition: used == 0
    onTrue:
      - type: target
        target: all
        effects:
          - type: attack
            hit:
              - type: damage
                damage: 2d6 + {strengthMod} + 1 [magical slashing]
            miss: []
            attackBonus: proficiencyBonus + strengthMod + 1
    onFalse: []
  - type: text
    text: >-
      The black blade of this sword is crafted from a mysterious arcane alloy.
      You gain a +1 bonus to attack and damage rolls made with this magic
      weapon. While the sword is on your person, you are immune to effects that
      turn undead.


      Dark Blessing. While holding the sword, you can use an action to give yourself 1d4 + 4 temporary hit points. This property can’t be used again until the next dusk. (`-choice dark`)


      Disheartening Strike. When you hit a creature with an attack using this weapon, you can fill the target with unsettling dread: the target has disadvantage on the next saving throw it makes before the end of your next turn. The creature ignores this effect if it’s immune to the frightened condition. Once you use this property, you can’t do so again until the next dusk. (`-choice disheartening`)
_v: 2
proper: false
