name: Bind the Wound
automation:
  - type: condition
    condition: BardLevel >= 5
    onTrue:
      - type: condition
        condition: BardLevel >= 10
        onTrue:
          - type: condition
            condition: BardLevel >= 15
            onTrue:
              - type: variable
                name: barddie
                value: "12"
            onFalse:
              - type: variable
                name: barddie
                value: "10"
            errorBehaviour: "false"
        onFalse:
          - type: variable
            name: barddie
            value: "8"
        errorBehaviour: "false"
    onFalse:
      - type: variable
        name: barddie
        value: "6"
    errorBehaviour: "false"
  - type: target
    target: all
    effects:
      - type: damage
        damage: "- 1d{barddie} - {wisdomMod}"
        overheal: false
  - type: text
    text: >-
      An experienced paladin instructed you in the basics of combat triage. When
      you or an ally within 5 feet of you receives healing of any kind, you may
      use your reaction to expend one use of your Bardic Inspiration and provide
      extra healing equal to the number on the Bardic Inspiration die roll +
      your Wisdom modifier (minimum of 1). You must have at least one hand free
      in order to quickly staunch the target’s wound.


      At 6th level, you have learned to identify a selection of useful herbs that you can carry with you. When providing additional healing with this trick you may also remove the poisoned or paralyzed condition from the target.


      At 14th level, you have developed a true knack for emergency triage. You may additionally remove a single disease affecting the target of this ability.
    title: Traveler's Trick - Bind the Wound
  - type: counter
    counter:
      id: 75
      typeId: 12168134
    amount: "1"
    allowOverflow: false
    errorBehaviour: warn
_v: 2
proper: true
verb: utilizes
activation_type: 4
