name: Conjure Woodland Spirit
automation:
  - type: counter
    counter:
      id: 75
      typeId: 12168134
    amount: "1"
    allowOverflow: false
    errorBehaviour: warn
  - type: condition
    condition: BardLevel >= 5
    onTrue:
      - type: condition
        condition: BardLevel >= 10
        onTrue:
          - type: condition
            condition: BardLevel >= 14
            onTrue:
              - type: condition
                condition: BardLevel > 14
                onTrue:
                  - type: target
                    target: self
                    effects:
                      - type: ieffect2
                        name: Conjure Woodland Spirit
                        duration: "100"
                        effects: null
                        attacks:
                          - attack:
                              name: Woodland Spirit Strike
                              automation:
                                - type: target
                                  target: all
                                  effects:
                                    - type: save
                                      stat: wis
                                      fail:
                                        - type: damage
                                          damage: 1d12 [slashing]
                                          overheal: false
                                        - type: ieffect2
                                          name: Restrained
                                          duration: null
                                          effects:
                                            attack_advantage: "-1"
                                            save_dis:
                                              - dex
                                          attacks: []
                                          buttons:
                                            - label: Escape
                                              automation:
                                                - type: target
                                                  target: self
                                                  effects:
                                                    - type: check
                                                      ability: athletics
                                                      success:
                                                        - type: remove_ieffect
                                                        - type: text
                                                          text: The target can break free by spending an action to make a Strength
                                                            (Athletics) check
                                                            against your
                                                            Traveler’s Trick
                                                            save DC.
                                                          title: Effect
                                              verb: null
                                              style: "1"
                                              defaultDC: 8 + proficiencyBonus + wisdomMod
                                              defaultAttackBonus: null
                                              defaultCastingMod: null
                                          end: false
                                          conc: false
                                          desc: Target is restrained and may take an action to make an athletics check to
                                            remove his effect.
                                          stacking: false
                                          save_as: null
                                          parent: null
                                          target_self: false
                                          tick_on_caster: false
                                      success: []
                                      dc: 8 + proficiencyBonus + wisdomMod
                                    - type: text
                                      text: >-
                                        Any enemy that moves into or leaves a space adjacent to the guardian
                                        spirit must make a Wisdom saving throw,
                                        taking magical slashing damage equal to
                                        your Bardic Inspiration die on a
                                        failure.


                                        At 6th level, your bond with the guardian spirit grows even deeper. Any creature dealt damage by your guardian spirit has their speed reduced to 0 for the rest of the turn.


                                        At 14th level, any Large or smaller creature who has their speed reduced to 0 by the guardian spirit is restrained for as long as you maintain your concentration, as your guardian spirit pins them in place. The target can break free by spending an action to make a Strength (Athletics) check against your Traveler’s Trick save DC.
                                      title: Effect
                              _v: 2
                            defaultDC: null
                            defaultAttackBonus: null
                            defaultCastingMod: null
                        buttons: []
                        end: false
                        conc: true
                        desc: null
                        stacking: false
                        save_as: null
                        parent: null
                        target_self: false
                        tick_on_caster: false
                onFalse:
                  - type: target
                    target: self
                    effects:
                      - type: ieffect2
                        name: Conjure Woodland Spirit
                        duration: "100"
                        effects: null
                        attacks:
                          - attack:
                              name: Woodland Spirit Strike
                              automation:
                                - type: target
                                  target: all
                                  effects:
                                    - type: save
                                      stat: wis
                                      fail:
                                        - type: damage
                                          damage: 1d10 [slashing]
                                          overheal: false
                                        - type: ieffect2
                                          name: Restrained
                                          duration: null
                                          effects:
                                            attack_advantage: "-1"
                                            save_dis:
                                              - dex
                                          attacks: []
                                          buttons:
                                            - label: Escape
                                              automation:
                                                - type: target
                                                  target: self
                                                  effects:
                                                    - type: check
                                                      ability: athletics
                                                      success:
                                                        - type: remove_ieffect
                                                        - type: text
                                                          text: The target can break free by spending an action to make a Strength
                                                            (Athletics) check
                                                            against your
                                                            Traveler’s Trick
                                                            save DC.
                                                          title: Effect
                                              verb: null
                                              style: "1"
                                              defaultDC: 8 + proficiencyBonus + wisdomMod
                                              defaultAttackBonus: null
                                              defaultCastingMod: null
                                          end: false
                                          conc: false
                                          desc: Target is restrained and may take an action to make an athletics check to
                                            remove his effect.
                                          stacking: false
                                          save_as: null
                                          parent: null
                                          target_self: false
                                          tick_on_caster: false
                                      success: []
                                      dc: 8 + proficiencyBonus + wisdomMod
                                    - type: text
                                      text: >-
                                        Any enemy that moves into or leaves a space adjacent to the guardian
                                        spirit must make a Wisdom saving throw,
                                        taking magical slashing damage equal to
                                        your Bardic Inspiration die on a
                                        failure.


                                        At 6th level, your bond with the guardian spirit grows even deeper. Any creature dealt damage by your guardian spirit has their speed reduced to 0 for the rest of the turn.


                                        At 14th level, any Large or smaller creature who has their speed reduced to 0 by the guardian spirit is restrained for as long as you maintain your concentration, as your guardian spirit pins them in place. The target can break free by spending an action to make a Strength (Athletics) check against your Traveler’s Trick save DC.
                                      title: Effect
                              _v: 2
                            defaultDC: null
                            defaultAttackBonus: null
                            defaultCastingMod: null
                        buttons: []
                        end: false
                        conc: true
                        desc: null
                        stacking: false
                        save_as: null
                        parent: null
                        target_self: false
                        tick_on_caster: false
                errorBehaviour: "false"
            onFalse:
              - type: target
                target: self
                effects:
                  - type: ieffect2
                    name: Conjure Woodland Spirit
                    duration: "100"
                    effects: null
                    attacks:
                      - attack:
                          name: Woodland Spirit Strike
                          automation:
                            - type: target
                              target: all
                              effects:
                                - type: save
                                  stat: wis
                                  fail:
                                    - type: damage
                                      damage: 1d10 [slashing]
                                      overheal: false
                                  success: []
                                  dc: 8 + proficiencyBonus + wisdomMod
                                - type: text
                                  text: >-
                                    Any enemy that moves into or leaves a space adjacent to the guardian
                                    spirit must make a Wisdom saving throw,
                                    taking magical slashing damage equal to your
                                    Bardic Inspiration die on a failure.


                                    At 6th level, your bond with the guardian spirit grows even deeper. Any creature dealt damage by your guardian spirit has their speed reduced to 0 for the rest of the turn.
                                  title: Effect
                          _v: 2
                        defaultDC: null
                        defaultAttackBonus: null
                        defaultCastingMod: null
                    buttons: []
                    end: false
                    conc: false
                    desc: null
                    stacking: false
                    save_as: null
                    parent: null
                    target_self: false
                    tick_on_caster: false
            errorBehaviour: "false"
        onFalse:
          - type: target
            target: self
            effects:
              - type: ieffect2
                name: Conjure Woodland Spirit
                duration: "100"
                effects: null
                attacks:
                  - attack:
                      name: Woodland Spirit Strike
                      automation:
                        - type: target
                          target: all
                          effects:
                            - type: save
                              stat: wis
                              fail:
                                - type: damage
                                  damage: 1d8 [slashing]
                                  overheal: false
                              success: []
                              dc: 8 + proficiencyBonus + wisdomMod
                            - type: text
                              text: Any enemy that moves into or leaves a space adjacent to the guardian
                                spirit must make a Wisdom saving throw, taking
                                magical slashing damage equal to your Bardic
                                Inspiration die on a failure.
                              title: Effect
                            - type: condition
                              condition: BardLevel >= 6
                              onTrue:
                                - type: text
                                  text: At 6th level, your bond with the guardian spirit grows even deeper. Any
                                    creature dealt damage by your guardian
                                    spirit has their speed reduced to 0 for the
                                    rest of the turn.
                                  title: Effect
                              onFalse: []
                              errorBehaviour: "false"
                      _v: 2
                    defaultDC: null
                    defaultAttackBonus: null
                    defaultCastingMod: null
                buttons: []
                end: false
                conc: false
                desc: null
                stacking: false
                save_as: null
                parent: null
                target_self: false
                tick_on_caster: false
        errorBehaviour: "false"
    onFalse:
      - type: target
        target: self
        effects:
          - type: ieffect2
            name: Conjure Woodland Spirit
            duration: "100"
            effects: null
            attacks:
              - attack:
                  name: Woodland Spirit Strike
                  automation:
                    - type: target
                      target: all
                      effects:
                        - type: save
                          stat: wis
                          fail:
                            - type: damage
                              damage: 1d6 [slashing]
                              overheal: false
                          success: []
                          dc: 8 + proficiencyBonus + wisdomMod
                        - type: text
                          text: Any enemy that moves into or leaves a space adjacent to the guardian
                            spirit must make a Wisdom saving throw, taking
                            magical slashing damage equal to your Bardic
                            Inspiration die on a failure.
                          title: Effect
                  _v: 2
                defaultDC: null
                defaultAttackBonus: null
                defaultCastingMod: null
            buttons: []
            end: false
            conc: true
            desc: null
            stacking: false
            save_as: null
            parent: null
            target_self: false
            tick_on_caster: false
    errorBehaviour: "false"
  - type: text
    text: >-
      A patient druid shared the secrets of forest magic with you. You can
      expend one use of your Bardic Inspiration as an action to conjure a forest
      guardian spirit in an unoccupied space you can see within 60 feet of you.
      The guardian spirit is Large, and takes the appearance of a spectral
      predatory cat. Any enemy that moves into or leaves a space adjacent to the
      guardian spirit must make a Wisdom saving throw, taking magical slashing
      damage equal to your Bardic Inspiration die on a failure. The guardian
      spirit will remain for as long as you concentrate on it, up to 10 minutes.


      At 6th level, your bond with the guardian spirit grows even deeper. Any creature dealt damage by your guardian spirit has their speed reduced to 0 for the rest of the turn.


      At 14th level, any Large or smaller creature who has their speed reduced to 0 by the guardian spirit is restrained for as long as you maintain your concentration, as your guardian spirit pins them in place. The target can break free by spending an action to make a Strength (Athletics) check against your Traveler’s Trick save DC.
    title: Traveler's Trick - Conjure Woodland Spirit
_v: 2
activation_type: 1
